Set the NodeID to the ExtensionObjects to the correct value #444
gopcua/opcua pull request #446
Opened 2021-07-15 14:04 UTC by siscia

The NodeID of the ExtensionObjects was set to a default, zero, value.
Even in cases where the type was actually registered by the library.

2021-07-15 14:05 UTC, siscia commented
Should we add test for this?

2021-07-15 15:18 UTC, siscia commented
Test are not passing!

2021-07-15 15:21 UTC, siscia commented
Call to make fails with:

```
=== RUN   TestCallMethod
cryptography is not installed, use of crypto disabled
cryptography is not installed, use of crypto disabled
Endpoints other than open requested but private key and certificate are not set.
Listening on 0.0.0.0:4840
=== RUN   TestCallMethod/ns=2;s=main
=== RUN   TestCallMethod/ns=2;s=main#01
=== RUN   TestCallMethod/ns=2;s=main#02
    method_test.go:71: opcua: unsupported type: int
Exception raised while parsing message from client, closing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/opcua/server/binary_server_asyncio.py", line 75, in _process_data
    ret = self.processor.process(hdr, buf)
  File "/usr/local/lib/python3.9/site-packages/opcua/server/uaprocessor.py", line 86, in process
    msg = self._connection.receive_from_header_and_body(header, body)
  File "/usr/local/lib/python3.9/site-packages/opcua/common/connection.py", line 315, in receive_from_header_and_body
    return self._receive(chunk)
  File "/usr/local/lib/python3.9/site-packages/opcua/common/connection.py", line 346, in _receive
    self._check_incoming_chunk(msg)
  File "/usr/local/lib/python3.9/site-packages/opcua/common/connection.py", line 290, in _check_incoming_chunk
    raise ua.UaError("Received chunk: {0} with wrong sequence expecting: {1}, received: {2}, spec says to close connection".format(chunk, self._peer_sequence_number, num))
opcua.ua.uaerrors._base.UaError: Received chunk: MessageChunk(Header(type:b'MSG', chunk_type:b'F', body_size:51, channel:6), SequenceHeader(SequenceNumber:7, RequestId:7 ), SymmetricAlgorithmHeader(TokenId:13 ), 39 bytes) with wrong sequence expecting: 5, received: 7, spec says to close connection
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1428, in _shutdown
  ```

2021-07-15 21:37 UTC, magiconair requested changes
The code isn't setting the type id in the `MustVariant` code path. This and the fact that the method returns a `Boolean` make the test fail. 

Additionally, I think we should refactor the `TypeRegistry` to guarantee that all keys are valid `NodeID`s.

2021-07-15 21:37 UTC, magiconair commented on uatest/method_server.py
> +    return [ua.Variant(ret, ua.VariantType.Boolean)]
The type should be `ua.VariantType.Int64` not `Boolean`

2021-07-15 21:37 UTC, magiconair commented on ua/extension_object.go
> +		t := eotypes.Lookup(v)
We should refactor the `TypeRegistry` to use `NodeID`s as keys so that we don't have to ignore the error below. I'll add a patch for this.

2021-07-15 21:37 UTC, magiconair commented on uatest/method_test.go
> +	i int
We should not use `int` and `uint` since they are platform dependent. 

```go
type Complex struct {
    i,j int64
}
```

2021-07-15 22:10 UTC, magiconair approved these changes

2021-07-15 22:10 UTC, magiconair commented
Fixed the test and added the change to refactor the type registry first. pls have a look

2021-07-16 08:46 UTC, siscia commented
Wonderful, thanks!

Maybe it make sense to implement the test correctly, what you think?

Ref: https://github.com/FreeOpcUa/python-opcua/issues/1364

2021-07-16 08:48 UTC, magiconair commented
What is wrong with the test?

2021-07-16 08:50 UTC, siscia commented
The result is hardcoded and not computed.

https://github.com/gopcua/opcua/pull/446/files#diff-078637d9373b2277a5d4cfbe1b2efc5fcc67b76c96df99916d627f952d6233e0R18

We are not actually reading the value from the object.

The byte array looks correct though!

2021-07-16 08:51 UTC, magiconair commented
ok, then change the test to actually compute the result but that should be enough.

2021-09-13 09:59 UTC, siscia commented
@magiconair I tried again to fix this, but with no success whatsoever.

If you want to take a look yourself it would be great.

2021-09-13 13:01 UTC, merged