implements write arrays
gopcua/opcua pull request #564
Opened 2022-03-08 10:50 UTC by siscia

Any reason why this was not implemented?

We have a use case with static size array, and it was returning an error.

2022-03-08 11:14 UTC, magiconair commented
Don't recall. Can you add a test?

2022-03-08 11:23 UTC, siscia commented
Do we have tests for the encoding part of the library?

I can't find them.

2022-03-08 11:31 UTC, magiconair commented
`us/decode_test.go`

2022-03-08 12:39 UTC, siscia commented
Found it!

I also implement the decoding!

2022-03-14 08:26 UTC, magiconair requested changes
I think the encode and decode functions can be the same for both slice and array and the type switch can be merged to `case reflect.Slice, reflect.Array:` to make it obvious. Maybe rename the functions to `writeSliceOrArray` and similar. The tests will ensure that it works.

2022-03-14 10:04 UTC, magiconair approved these changes
After looking at #566 which merges the functions it became clear that this approach doesn't increase readability. There are too many subtle differences. So we go with separate functions for encoding slices and arrays.

I've found a fast path for byte arrays, updated the tests and made the error messages consistent. 

LGTM now

2022-03-14 10:07 UTC, merged