Add Fallback to set session.AuthPolicyURI
gopcua/opcua pull request #706
Opened 2024-01-19 10:02 UTC by alexanderpetrenz

I´m using the lib in Telegraf. In a Certificate based connection I had the problem that the library raised the error
`error creating session signature: opcua: unsupported security policy`

I was able to track the origin of that issue: The field AuthPolicyURI of the session config is not set.

When setting up the Connection the library retrieves the endpoints from the server. The Server is providing one endpoint:
```
Endpoint1: policy: http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, epurl: XXXXX, secmode: 3, transportProfileURI: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary, seclevel: 4

UserIdentityTokens of Endpoint
tokentype: , issuerendpointurl , policyid 0, security policy uri: , token type: 0
tokentype: , issuerendpointurl , policyid 1, security policy uri: , token type: 1
tokentype: , issuerendpointurl , policyid 2, security policy uri: , token type: 2
```

During connection setup the telegraf opcua client is calling the SecurityFromEndpoint method of the opcua library. In that method the relevant userIdeentityToken from the received Endpoint is used to set the session.AuthPolicyURI field. However the field for the security policy uri of the relevant UserIdentityToken (token type: 2 in my case) is empty. As a result the AuthPolicyURI will get no value and the connection does fail.

I was able to fix that issue for that specific server by adding some fallback logic: When the relevant UserIdentityToken does not provide the needed security policy, that one from the endpoint will be used.

However I can´t say if this change is safe in general.

2024-01-24 09:00 UTC, magiconair commented
Hmm, good point. Is there something in the spec which describes the desired behavior?

2024-01-24 09:00 UTC, magiconair commented
Can we add a test for that?

2024-01-24 10:48 UTC, alexanderpetrenz commented
> Hmm, good point. Is there something in the spec which describes the desired behavior?

I´m not familiar in detail with the spec. However I guess I found some relevant part of it [here](https://reference.opcfoundation.org/Core/Part4/v105/docs/7.41), which says

> If this [SecurityPolicy](https://reference.opcfoundation.org/search/357?t=SecurityPolicy) is null or empty then the [Client](https://reference.opcfoundation.org/search/357?t=Client) uses the [SecurityPolicy](https://reference.opcfoundation.org/search/357?t=SecurityPolicy) in the [EndpointDescription](https://reference.opcfoundation.org/search/357?t=EndpointDescription).

2024-01-24 12:54 UTC, alexanderpetrenz commented
> Can we add a test for that?

I can, but that might take a while. Looking at the current tests, I wasn´t able to find out yet, how the python components are triggered when a go test is executed. Is there some documentation on this?

2024-02-11 21:00 UTC, alpex8 commented
I added a check on AuthPolicyURI property in client.go to make sure it is always set. However with check several integration tests will fail since they seem to rely on the anonymous policy which if I understood that correct seems to be handled as a default case.

On the other hand when that default is set in `config.go` line 401 some advice is given that most clients should call the SecurityFromEndpoint option before - which is exactly where I added my fallback condition.

I a bit stuck now because as I didn´t find some information in the spec saying that each session must have an AuthPolicyUri set.
I could just remove that check, which would make all tests pass. 

Do you have further requirements what the test case should cover?

2025-01-22 06:42 UTC, magiconair requested changes
Hi @alpex8, I am picking up the slack a bit. I think you can simplify the change to 

```go
			setPolicyID(cfg.session.UserIdentityToken, t.PolicyID)
			cfg.session.AuthPolicyURI = t.SecurityPolicyURI
			if cfg.session.AuthPolicyURI == "" {
				cfg.session.AuthPolicyURI = ep.SecurityPolicyURI
			}
```

and I was thinking of a unit test in `config_test.go`. I'll have a look at the integration test.

2025-01-22 06:43 UTC, magiconair commented
Could you also rebase your change to `main`?

2025-03-16 07:25 UTC, magiconair commented
I've rebased the branch, added a unit test and fixed the integration test. I think the fallback in `config.go` is enough and we don't need the extra check in `client.go`.

Since I can't push to your repo I've reworked the change in #779 but we will keep the discussion here.

2025-03-17 05:59 UTC, closed without merging