subscription: add SetMonitoringMode functionality
gopcua/opcua pull request #712
Opened 2024-02-06 03:52 UTC by jackchenjc

closes #711

Simply add the following code to `examples/subscribe/subscribe.go` can test this new feature
```
resp, err := sub.SetMonitoringMode(ctx, ua.MonitoringModeSampling, res.Results[0].MonitoredItemID)
if err != nil || resp.Results[0] != ua.StatusOK {
	log.Fatal(err)
}
```

2024-02-06 07:01 UTC, jackchenjc commented
Not sure if we should update `item.req.MonitoringMode` while getting `ua.StatusOK`.

2024-04-19 08:04 UTC, kung-foo requested changes

2024-04-19 08:04 UTC, kung-foo commented on subscription.go
> +			return nil, fmt.Errorf("sub %d: cannot set monitoring mode for unknown monitored item id: %d", s.SubscriptionID, id)
returning here leaves the mutex locked

2024-04-19 10:48 UTC, jackchenjc commented on subscription.go
> +			return nil, fmt.Errorf("sub %d: cannot set monitoring mode for unknown monitored item id: %d", s.SubscriptionID, id)
Done and also fixed the one in `ModifyMonitoredItems`.

2024-04-22 07:05 UTC, kung-foo requested changes
Ah, https://github.com/gopcua/opcua/blob/v0.5.3/README.md?plain=1#L206 needs an update as well. Otherwise LGTM

2024-04-22 07:42 UTC, kung-foo approved these changes

2024-04-22 07:42 UTC, merged